---
title: "SLoafing_Final"
format:
  apaquarto-pdf:
    documentmode: man
    a4paper: true
    pdf-engine: lualatex
    keep-tex: false
editor: visual
lang: en

authors:
  - name: "Samuel Riess"
    corresponding: true
    email: "Samuel.riess@campus.lmu.de"
    roles:
      - writing
      - conceptualization
    affiliations:
      - id: "lmu"
        name: "Ludwig-Maximilians-Universität München, Munich, Germany"
        department: "Department of Psychology"

bibiography: Base_Literature/references.bib
keywords: 
- formalization 
- Social impact theory 
- social loafing

abstract: "insert abstract here later on"
bibliography: references.bib
---

```{r setup}
#| echo: false 
#| include: false 

# loading of the necessary packages 
library(papaja) # for an automatically outut of results, p.e. apa_print()
library(flextable) # for displaying tables in APA-Style 
library(pwr) # for the power-Analysis 

#if we source a R-document, it runs in advance and we get all created objects from that file aswell for that document/report
source("simulation/01_base.R")
```

# Introduction

# Objective

In this report, we formalize an existing psychological theory to test the relation between the emerging phenomena and the corresponding data by means of a computational model, based on the underlying theory. Following the methodological framework outlined by Borsdoom ([@borsboom2021]), we generate simulated data for a fictional experiment inspired by the original study in which the phenomenon was first described. We are mainly interested in replicating key empirical findings associated with the phenomenon and to demonstrate that the model is capable of reproducing the phenomenon across different hypothetical scenarios. The need for such work is grounded in broader concerns within psychological science, known under terms like "reproducibility crisis" (citation Borsboom). Hence, our aim is to take a closer look at the relationship between the underlying theory and the emerging phenomenon, evaluating how well the theoretical assumptions can account for the observed effects.

# Introduction of the theory.

We chose a social psychology theory for that the emerged phenomena contains clearly observable variables, both input and output ones. The theory, named "social impact theory", was first mentioned in 1973 (citation Latané 1973), but the large framework with all supposed mechanisms and effects was published a few years later (citation Latané theory Hauptpaper). Between these publications, Latané published "Many Hands Make Light The Work: The Causes and Consequences of Social Loafing" in which the term "social loafing" was first defined. There, they tried to explain it using the first approaches of social loafing theory. For adding more depth to the phenomenon we are referring to an underlying mechanism, named "Effort Matching". 

## Core constructs

Our formalization is grounded on some core constructs. These are orientated at citations we withdrawed directly from the existing research. Some constructs were specified differently over the whole report, so we aimed to label them in a way that serves a greater interpretation. Of course, these labels are our own understanding of the constructs, further reseachers could focus on other elements. Furthermore, the scope is strongly limited to the main social loafing research, we only differ if there's some special need or cause for it.



All constructs and their sources can be seen in (Table 1).






## Identification of the relevant Phenomena

In (hier Zitation einfügen), the social loafing is described as followed: "People exhibit a sizeable decrease in individual effort when performing in groups as compared to when they perform alone". In the following sections, we aimed to create a link between this phenomena and out formalization of the social impact theory.

# Method

## used software

Throughout our formalization, we use the Visual Argument Strucure Tool (VAST, citation VAST) to build a graphic visualization of the theory and resulting mechanisms. With this methodology, we are able to define realtionsships, out unterstanding of core constructs and the mechanisms that take place in the process of social loafing and effort matching. For the computation of our simulated Data, we used R(hier Versionsnummer einfügen). Our graphic representation of the formalized theory was enabled throughout the application draw.io in which we created our VAST model.

## Formalization of the Theory

We used the VAST (Visual Argument Structure Tool) as a graphic form of formalization for our theory. Furhter information about the VAST and its application can be found in (hier Zitation einfügen). In the process, it was crucial to limit our scope, referring to both theory and phenomena. The main goal should be understandability, not the whole integrity of the full theory.

## Variables

## Relationships

# The formal model

## Development of a formal model

## Testing the formal model

## Evaluation of the formal model

# Discussion

# References

# Appendix
